# This file automatize the testing of SimGrid on Windows using the appveyor.com continuous integration service
#
# Build logs: https://ci.appveyor.com/project/simgrid/simgrid

# Documentation: https://www.appveyor.com/docs/
#                https://www.appveyor.com/docs/installed-software/

os: Visual Studio 2015
version: "{build}"
clone_depth: 1

# scripts that are called at very beginning, before repo cloning
init:
- git config --global core.longpaths true
- git config --global core.autocrlf input

environment:
  global:
    BOOST_ROOT: C:\Libraries\boost_1_60_0

install:
# Strawberry perl is the one to work with gcc; AppVeyor provides ActiveState perl, which is the one to work with visual.
# This package is so outdated and broken that we cannot use it anymore. So we build without perl
# - choco install --limit-output strawberryperl --version 5.20.1.1
# - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
# Lua 
#- choco install lua53
# We need python v3
- SET PATH=C:\Python35-x64;%PATH% # We need python v3
# Appveyor does not provide a 64bits mingw-w64, only a 32 bits
- choco install --limit-output mingw
- SET PATH=C:\tools\mingw64\bin;%PATH% # Our mingw must be placed before Perl in the path
# Work around a bug on appveyor where the default sh is not the one I expect
- rename "C:\Program Files\Git\usr\bin\sh.exe" "sh-ignored.exe"

build_script:
- cmake -G "MinGW Makefiles" -Denable_lua=OFF -Denable_documentation=OFF -Denable_java=ON -Denable_smpi=OFF -Denable_mallocators=OFF -Denable_lto=OFF .
- C:\tools\mingw64\bin\mingw32-make.exe VERBOSE=1

- ctest --output-on-failure -R java

artifacts:
- path: simgrid.jar
  name: jarfile

# notifications:
# - irc: "irc.debian.org#simgrid" # Not implemented by AppVeyor yet :(



