#Â NS3 is disabled because the version in ubuntu precise does not lead
# to the same timings (precision error?)
# Reenable with 
#   cmake -Denable_ns3
#   apt-get libns3-dev ns3
#
#
language: cpp
compiler:
   - gcc
#  - clang # boost 1.48 raises an error on clang:
#            /usr/include/boost/signals2/detail/auto_buffer.hpp:565:57: error:
#              reference to non-static member function must be called
#                        std::uninitialized_fill( buffer_, buffer_ + size, init_value );
#                                                                    ^~~~
addons:
  apt: # Get recent versions of the compiler, even on Ubuntu Precise
      sources:
      - ubuntu-toolchain-r-test
      packages:
      - gcc-4.7
      - g++-4.7
#      - clang
# Install libboost-chrono1.48-dev to get boost 1.48 on Ubuntu Precise. What we really want is libboost-dev libboost-all-dev
# Still need sudo for update-alternatives
before_install:
   - if [ ${TRAVIS_OS_NAME} = 'linux' ] ; then sudo add-apt-repository --yes ppa:kubuntu-ppa/backports ; fi # cmake higher than 2.8.7
   - if [ ${TRAVIS_OS_NAME} = 'linux' ] ; then sudo apt-get update  -qq ; fi
   - if [ ${TRAVIS_OS_NAME} = 'linux' ] ; then sudo apt-get install -y cmake valgrind default-jdk gfortran liblua5.1-dev lua5.1 libboost-chrono1.48-dev ; fi
   - if [ ${TRAVIS_OS_NAME} = 'linux' ] ; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 50 ; fi
   - if [ ${TRAVIS_OS_NAME} = 'linux' ] ; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.7 50 ; fi
script:
   - cmake -Denable_documentation=OFF -Denable_coverage=OFF -Denable_java=ON -Denable_model-checking=OFF -Denable_lua=ON -Denable_compile_optimizations=ON -Denable_smpi=ON -Denable_smpi_MPICH3_testsuite=OFF -Denable_compile_warnings=ON . && make VERBOSE=1 && ctest --output-on-failure --timeout 100
branches:
  only:
     - master
notifications:
  recipients:
    - martin.quinson@loria.fr
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.debian.org#simgrid"
  template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
os:
  - linux
  - osx
