language: cpp
compiler:
   - gcc
#   - clang # does not work for us on debian stable (boost is too old there)
before_install: 
   - sudo apt-get update  -qq
   - sudo apt-get install -y cmake doxygen valgrind default-jdk gfortran liblua5.1-dev lua5.1 libboost-dev libboost-all-dev libns3-dev ns3
script:
   - cmake -Denable_documentation=OFF -Denable_coverage=OFF -Denable_ns3=ON -Denable_java=ON -Denable_model-checking=OFF -Denable_lua=ON -Denable_compile_optimizations=ON -Denable_smpi=ON -Denable_smpi_MPICH3_testsuite=ON -Denable_compile_warnings=ON . && make && ctest --output-on-failure --timeout 100
branches:
  only:
     - master
notifications:
  recipients:
    - martin.quinson@loria.fr
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.debian.org#simgrid"
  template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
os:
  - linux
  - osx
  - windows
