# This is the configuration file for the https://circleci.com/ continuous integration server
#
# Copyright (c) 2017-2020. The SimGrid team. All rights reserved.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the license (GNU LGPL) which comes with this package.

default: &default
  docker:
    - image: simgrid/build-deps

version: 2.0
jobs:
  build:
    <<: *default
    steps:
      - checkout
      - run:
          name: Configure, build and test da stuff
          command: |
            mkdir _build && cd _build
            cmake -Denable_documentation=OFF -Denable_coverage=ON -Denable_java=ON -Denable_MSG=ON -Denable_model-checking=OFF -Denable_lua=OFF -Denable_compile_optimizations=OFF -Denable_smpi=ON -Denable_smpi_MPICH3_testsuite=OFF -Denable_compile_warnings=ON ..
            make -j4 tests && ctest -j4 --output-on-failure
